[build]
  command = "npm run build"
  publish = "dist/rent-hub/browser"

[build.environment]
  NODE_VERSION = "20.19.0"  # or "22.12.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
